baseURL = "http://RegulatableML.github.io/"
languageCode = "en-us"
title = "Regulatable ML Workshop"
theme = "ananke"

defaultContentLanguage = "en"


[menu]
# Main menu
[[menu.main]]
    name       = "Overview"
    identifier = "menu.overview"
    url        = "/#overview"
    weight     = 1
[[menu.main]]
    name       = "Call for Papers"
    identifier = "menu.cfp"
    url        = "/cfp"
    weight     = 2
[[menu.main]]
    name       = "Keynote Talks"
    identifier = "menu.kt"
    url        = "/#keynote-talks"
    weight     = 3
[[menu.main]]
    name       = "Panel Discussion"
    identifier = "menu.pd"
    url        = "/#panel-discussion"
    weight     = 4
[[menu.main]]
    name       = "Schedule"
    identifier = "menu.sch"
    url        = "/#schedule"
    weight     = 5
[[menu.main]]
    name       = "Organization"
    identifier = "menu.organization"
    url        = "/#organizers"
    weight     = 6
[[menu.main]]
    name       = "Accepted Papers"
    identifier = "menu.ap"
    url        = "https://openreview.net/group?id=NeurIPS.cc/2023/Workshop/RegML#tab-accept"
    weight     = 7


[params]
	custom_css = ["custom.css"]
	# body_classes = "calibre bg-near-white"