baseURL = "https://RegulatableML.github.io/"
languageCode = "en-us"
title = "Regulatable ML Workshop"
theme = "ananke"

defaultContentLanguage = "en"


[menu]
# Main menu
[[menu.main]]
    name       = "Overview"
    identifier = "menu.overview"
    url        = "/#overview"
    weight     = 1
[[menu.main]]
    name       = "Call for Papers"
    identifier = "menu.cfp"
    url        = "/cfp"
    weight     = 2
[[menu.main]]
    name       = "Organization"
    identifier = "menu.organization"
    url        = "/#organizers"
    weight     = 7
[[menu.main]]
    name       = "Past Editions"
    identifier = "menu.past"
    url        = "/#past-editions"
    weight     = 8
[[menu.main]]
    name       = "RegML 2024"
    identifier = "menu.past.neurips2024"
    url        = "/neurips2024"
    parent     = "menu.past"
    weight     = 9
[[menu.main]]
    name       = "RegML 2023"
    identifier = "menu.past.neurips2023"
    url        = "/neurips2023"
    parent     = "menu.past"
    weight     = 10

# Disqus configuration (disabled for now)
disqusShortname = ""

[params]
	custom_css = ["custom.css"]
	# body_classes = "calibre bg-near-white"
	# Disable Disqus comments
	commentoEnable = false
	disqusShortname = ""
